// swift-tools-version: 5.9
import PackageDescription

// whisper.cpp is vendored as a submodule under the CWhisper target so SwiftPM
// can compile its sources directly (paths are relative to Sources/CWhisper).
let w = "whisper.cpp"
let ggml = "\(w)/ggml/src"

let package = Package(
    name: "VoiceType",
    platforms: [.macOS(.v14)],
    targets: [
        // C/C++/ObjC target: whisper + ggml + Metal backend, no cmake.
        .target(
            name: "CWhisper",
            path: "Sources/CWhisper",
            // The submodule lives inside this target's path, so exclude
            // everything that isn't a compiled source. Critically, exclude both
            // `.metal` files: SwiftPM would otherwise auto-compile them as Metal
            // resources (needs the Xcode Metal toolchain, which we deliberately
            // avoid) — the shader is embedded via ggml-metal-embed.s instead.
            exclude: [
                "ggml-metal-embed.metal",            // generated; .incbin'd, not compiled
                "\(ggml)/ggml-metal/ggml-metal.metal",
                // non-source subtrees of the submodule
                "\(w)/examples", "\(w)/bindings", "\(w)/models", "\(w)/samples",
                "\(w)/tests", "\(w)/scripts", "\(w)/ci", "\(w)/cmake",
                "\(w)/media", "\(w)/grammars",
                // ggml backends we don't build
                "\(ggml)/ggml-cann", "\(ggml)/ggml-cuda", "\(ggml)/ggml-hip",
                "\(ggml)/ggml-musa", "\(ggml)/ggml-opencl", "\(ggml)/ggml-openvino",
                "\(ggml)/ggml-rpc", "\(ggml)/ggml-sycl", "\(ggml)/ggml-virtgpu",
                "\(ggml)/ggml-vulkan", "\(ggml)/ggml-webgpu", "\(ggml)/ggml-zdnn",
                "\(ggml)/ggml-zendnn", "\(ggml)/ggml-hexagon",
                // unused CPU sub-backends
                "\(ggml)/ggml-cpu/amx", "\(ggml)/ggml-cpu/kleidiai",
                "\(ggml)/ggml-cpu/spacemit", "\(ggml)/ggml-cpu/cmake",
            ],
            sources: [
                "\(w)/src/whisper.cpp",
                // ggml core
                "\(ggml)/ggml.c",
                "\(ggml)/ggml.cpp",
                "\(ggml)/ggml-alloc.c",
                "\(ggml)/ggml-backend.cpp",
                "\(ggml)/ggml-backend-reg.cpp",
                "\(ggml)/ggml-backend-meta.cpp",
                "\(ggml)/ggml-backend-dl.cpp",
                "\(ggml)/ggml-opt.cpp",
                "\(ggml)/ggml-quants.c",
                "\(ggml)/ggml-threading.cpp",
                "\(ggml)/gguf.cpp",
                // CPU backend
                "\(ggml)/ggml-cpu/ggml-cpu.c",
                "\(ggml)/ggml-cpu/ggml-cpu.cpp",
                "\(ggml)/ggml-cpu/ops.cpp",
                "\(ggml)/ggml-cpu/vec.cpp",
                "\(ggml)/ggml-cpu/binary-ops.cpp",
                "\(ggml)/ggml-cpu/unary-ops.cpp",
                "\(ggml)/ggml-cpu/quants.c",
                "\(ggml)/ggml-cpu/repack.cpp",
                "\(ggml)/ggml-cpu/traits.cpp",
                "\(ggml)/ggml-cpu/hbm.cpp",
                "\(ggml)/ggml-cpu/arch/arm/quants.c",
                "\(ggml)/ggml-cpu/arch/arm/repack.cpp",
                "\(ggml)/ggml-cpu/arch/arm/cpu-feats.cpp",
                "\(ggml)/ggml-cpu/llamafile/sgemm.cpp",
                // Metal backend
                "\(ggml)/ggml-metal/ggml-metal.cpp",
                "\(ggml)/ggml-metal/ggml-metal-device.m",
                "\(ggml)/ggml-metal/ggml-metal-device.cpp",
                "\(ggml)/ggml-metal/ggml-metal-context.m",
                "\(ggml)/ggml-metal/ggml-metal-common.cpp",
                "\(ggml)/ggml-metal/ggml-metal-ops.cpp",
                // BLAS / Accelerate backend
                "\(ggml)/ggml-blas/ggml-blas.cpp",
                // Metal shader embedded as a data blob; generated by
                // scripts/embed_metal_shader.sh before `swift build`.
                "ggml-metal-embed.s",
            ],
            publicHeadersPath: "include",
            cSettings: [
                .headerSearchPath("\(w)/include"),
                .headerSearchPath("\(w)/ggml/include"),
                .headerSearchPath("\(w)/ggml/src"),
                .headerSearchPath("\(w)/ggml/src/ggml-cpu"),
                .define("GGML_USE_CPU"),
                .define("GGML_USE_METAL"),
                .define("GGML_METAL_EMBED_LIBRARY"),
                .define("GGML_USE_BLAS"),
                .define("GGML_USE_ACCELERATE"),
                .define("GGML_BLAS_USE_ACCELERATE"),
                .define("ACCELERATE_NEW_LAPACK"),
                .define("ACCELERATE_LAPACK_ILP64"),
                // Version strings normally injected by cmake; provide them so
                // ggml_version()/whisper_version() compile.
                .define("GGML_VERSION", to: "\"0.15.3\""),
                .define("GGML_COMMIT", to: "\"0ae02cd\""),
                .define("WHISPER_VERSION", to: "\"1.8.0\""),
                .define("NDEBUG", .when(configuration: .release)),
                .define("_DARWIN_C_SOURCE"),
                // ggml's Metal .m files use manual reference counting (explicit
                // -release, implicit void*↔id casts), so disable ARC for the
                // target's ObjC sources. -Qunused-arguments silences the flag
                // being unused on .c/.cpp compiles.
                .unsafeFlags(["-Wno-shorten-64-to-32", "-fno-objc-arc", "-Qunused-arguments"]),
            ],
            cxxSettings: [
                .headerSearchPath("\(w)/include"),
                .headerSearchPath("\(w)/ggml/include"),
                .headerSearchPath("\(w)/ggml/src"),
                .headerSearchPath("\(w)/ggml/src/ggml-cpu"),
                .define("GGML_USE_CPU"),
                .define("GGML_USE_METAL"),
                .define("GGML_METAL_EMBED_LIBRARY"),
                .define("GGML_USE_BLAS"),
                .define("GGML_USE_ACCELERATE"),
                .define("GGML_BLAS_USE_ACCELERATE"),
                .define("ACCELERATE_NEW_LAPACK"),
                .define("ACCELERATE_LAPACK_ILP64"),
                // Version strings normally injected by cmake; provide them so
                // ggml_version()/whisper_version() compile.
                .define("GGML_VERSION", to: "\"0.15.3\""),
                .define("GGML_COMMIT", to: "\"0ae02cd\""),
                .define("WHISPER_VERSION", to: "\"1.8.0\""),
                .define("NDEBUG", .when(configuration: .release)),
            ],
            linkerSettings: [
                .linkedFramework("Foundation"),
                .linkedFramework("Metal"),
                .linkedFramework("MetalKit"),
                .linkedFramework("Accelerate"),
            ]
        ),
        .executableTarget(
            name: "VoiceType",
            dependencies: ["CWhisper"],
            path: "Sources/VoiceType",
            swiftSettings: [
                // The CWhisper module map's shim #includes whisper.h, which in
                // turn includes ggml.h/ggml-cpu.h. SwiftPM doesn't propagate the
                // C target's headerSearchPaths to the importer, so make those
                // dirs visible to the Clang importer here (paths relative to the
                // package root).
                .unsafeFlags([
                    "-Xcc", "-ISources/CWhisper/whisper.cpp/include",
                    "-Xcc", "-ISources/CWhisper/whisper.cpp/ggml/include",
                ]),
            ],
            linkerSettings: [
                .linkedFramework("AppKit"),
                .linkedFramework("AVFoundation"),
                .linkedFramework("ApplicationServices"),
            ]
        ),
    ],
    cxxLanguageStandard: .cxx17
)
