// swift-tools-version: 5.9
import PackageDescription

// whisper.cpp is vendored as a submodule under the CWhisper target so SwiftPM
// can compile its sources directly (paths are relative to Sources/CWhisper).
//
// Package.swift is a HOST tool: SwiftPM compiles and runs this manifest on the
// build machine, so `#if arch(arm64)` reflects the machine running SwiftPM — NOT
// the `--arch` passed to `swift build`. Consequences:
//   - Apple Silicon (arm64) selects the arm64 branch: whisper + ggml + the Metal
//     backend — byte-for-byte the pre-Phase-5 build.
//   - Intel (x86_64) selects the #else branch: a CPU-only build (x86 CPU sources,
//     AVX2/FMA/F16C, Accelerate/BLAS; no Metal at all).
//   - To exercise the x86 branch on an Apple Silicon host you must run the WHOLE
//     toolchain under Rosetta: `arch -x86_64 swift build -c release`.
//     `swift build --arch x86_64` does NOT — it still runs this manifest as arm64.
let w = "whisper.cpp"
let ggml = "\(w)/ggml/src"

// --- Pieces shared by both arches (composed by each branch below) ------------

// Header search paths, identical in every C/C++ settings block on both arches.
let headerPaths = [
    "\(w)/include",
    "\(w)/ggml/include",
    "\(w)/ggml/src",
    "\(w)/ggml/src/ggml-cpu",
]

// Version strings normally injected by cmake; provided here so
// ggml_version()/whisper_version() compile. Shared by C and C++ settings.
let versionDefines: [(String, String)] = [
    ("GGML_VERSION", "\"0.15.3\""),
    ("GGML_COMMIT", "\"0ae02cd\""),
    ("WHISPER_VERSION", "\"1.8.0\""),
]

// Arch-agnostic sources: whisper + ggml core + the shared CPU backend +
// llamafile sgemm + the BLAS/Accelerate backend. Arch-specific CPU sources and
// the Metal backend are appended per-branch below.
let sharedSources = [
    "\(w)/src/whisper.cpp",
    // ggml core
    "\(ggml)/ggml.c",
    "\(ggml)/ggml.cpp",
    "\(ggml)/ggml-alloc.c",
    "\(ggml)/ggml-backend.cpp",
    "\(ggml)/ggml-backend-reg.cpp",
    "\(ggml)/ggml-backend-meta.cpp",
    "\(ggml)/ggml-backend-dl.cpp",
    "\(ggml)/ggml-opt.cpp",
    "\(ggml)/ggml-quants.c",
    "\(ggml)/ggml-threading.cpp",
    "\(ggml)/gguf.cpp",
    // CPU backend (arch-agnostic)
    "\(ggml)/ggml-cpu/ggml-cpu.c",
    "\(ggml)/ggml-cpu/ggml-cpu.cpp",
    "\(ggml)/ggml-cpu/ops.cpp",
    "\(ggml)/ggml-cpu/vec.cpp",
    "\(ggml)/ggml-cpu/binary-ops.cpp",
    "\(ggml)/ggml-cpu/unary-ops.cpp",
    "\(ggml)/ggml-cpu/quants.c",
    "\(ggml)/ggml-cpu/repack.cpp",
    "\(ggml)/ggml-cpu/traits.cpp",
    "\(ggml)/ggml-cpu/hbm.cpp",
    "\(ggml)/ggml-cpu/llamafile/sgemm.cpp",
    // BLAS / Accelerate backend
    "\(ggml)/ggml-blas/ggml-blas.cpp",
]

// Excludes shared by both arches. The submodule lives inside the target path, so
// everything that isn't a compiled source is excluded. `ggml-metal.metal` is
// excluded on BOTH arches: it still exists in the submodule and SwiftPM would
// otherwise try to Metal-compile it as a resource (needs the Xcode Metal
// toolchain, which we deliberately avoid).
let sharedExcludes = [
    "\(ggml)/ggml-metal/ggml-metal.metal",
    // non-source subtrees of the submodule
    "\(w)/examples", "\(w)/bindings", "\(w)/models", "\(w)/samples",
    "\(w)/tests", "\(w)/scripts", "\(w)/ci", "\(w)/cmake",
    "\(w)/media", "\(w)/grammars",
    // ggml backends we don't build
    "\(ggml)/ggml-cann", "\(ggml)/ggml-cuda", "\(ggml)/ggml-hip",
    "\(ggml)/ggml-musa", "\(ggml)/ggml-opencl", "\(ggml)/ggml-openvino",
    "\(ggml)/ggml-rpc", "\(ggml)/ggml-sycl", "\(ggml)/ggml-virtgpu",
    "\(ggml)/ggml-vulkan", "\(ggml)/ggml-webgpu", "\(ggml)/ggml-zdnn",
    "\(ggml)/ggml-zendnn", "\(ggml)/ggml-hexagon",
    // unused CPU sub-backends
    "\(ggml)/ggml-cpu/amx", "\(ggml)/ggml-cpu/kleidiai",
    "\(ggml)/ggml-cpu/spacemit", "\(ggml)/ggml-cpu/cmake",
]

// --- Arch-specific configuration (selected by the HOST arch; see header) ------
#if arch(arm64)
// Apple Silicon: today's Metal build, unchanged.
let archSources = [
    // arm CPU kernels
    "\(ggml)/ggml-cpu/arch/arm/quants.c",
    "\(ggml)/ggml-cpu/arch/arm/repack.cpp",
    "\(ggml)/ggml-cpu/arch/arm/cpu-feats.cpp",
    // Metal backend
    "\(ggml)/ggml-metal/ggml-metal.cpp",
    "\(ggml)/ggml-metal/ggml-metal-device.m",
    "\(ggml)/ggml-metal/ggml-metal-device.cpp",
    "\(ggml)/ggml-metal/ggml-metal-context.m",
    "\(ggml)/ggml-metal/ggml-metal-common.cpp",
    "\(ggml)/ggml-metal/ggml-metal-ops.cpp",
    // Metal shader embedded as a data blob; generated by
    // scripts/embed_metal_shader.sh before `swift build`.
    "ggml-metal-embed.s",
]
// The generated embed shader is .incbin'd, not compiled — exclude it so SwiftPM
// doesn't treat it as a Metal resource. (x86 never generates this file, so its
// exclude is arm-only to avoid warning on a non-existent path.)
let archExcludes = ["ggml-metal-embed.metal"]
let cMetalDefines: [CSetting] = [.define("GGML_USE_METAL"), .define("GGML_METAL_EMBED_LIBRARY")]
let cxxMetalDefines: [CXXSetting] = [.define("GGML_USE_METAL"), .define("GGML_METAL_EMBED_LIBRARY")]
// ggml's Metal .m files use manual reference counting (explicit -release,
// implicit void*<->id casts), so disable ARC for the target's ObjC sources;
// -Qunused-arguments silences the flag being unused on .c/.cpp compiles.
let cArchFlags = ["-fno-objc-arc", "-Qunused-arguments"]
let cxxArchSettings: [CXXSetting] = []
let archFrameworks: [LinkerSetting] = [.linkedFramework("Metal"), .linkedFramework("MetalKit")]
#else
// Intel (x86_64): CPU-only build. No Metal sources/defines/frameworks. x86 CPU
// kernels compiled with AVX2/FMA/F16C; Accelerate/BLAS kept.
let archSources = [
    "\(ggml)/ggml-cpu/arch/x86/quants.c",
    "\(ggml)/ggml-cpu/arch/x86/repack.cpp",
    "\(ggml)/ggml-cpu/arch/x86/cpu-feats.cpp",
]
let archExcludes: [String] = []
let cMetalDefines: [CSetting] = []
let cxxMetalDefines: [CXXSetting] = []
let cArchFlags = ["-mavx2", "-mfma", "-mf16c"]
let cxxArchSettings: [CXXSetting] = [.unsafeFlags(["-Wno-shorten-64-to-32", "-mavx2", "-mfma", "-mf16c"])]
let archFrameworks: [LinkerSetting] = []
#endif

// --- Composed settings (typed locals keep the type-checker fast) -------------
let cSettings: [CSetting] =
    headerPaths.map { CSetting.headerSearchPath($0) }
    + [.define("GGML_USE_CPU")]
    + cMetalDefines
    + [
        .define("GGML_USE_BLAS"),
        .define("GGML_USE_ACCELERATE"),
        .define("GGML_BLAS_USE_ACCELERATE"),
        .define("ACCELERATE_NEW_LAPACK"),
        .define("ACCELERATE_LAPACK_ILP64"),
    ]
    + versionDefines.map { CSetting.define($0.0, to: $0.1) }
    + [
        .define("NDEBUG", .when(configuration: .release)),
        .define("_DARWIN_C_SOURCE"),
        .unsafeFlags(["-Wno-shorten-64-to-32"] + cArchFlags),
    ]

let cxxSettings: [CXXSetting] =
    headerPaths.map { CXXSetting.headerSearchPath($0) }
    + [.define("GGML_USE_CPU")]
    + cxxMetalDefines
    + [
        .define("GGML_USE_BLAS"),
        .define("GGML_USE_ACCELERATE"),
        .define("GGML_BLAS_USE_ACCELERATE"),
        .define("ACCELERATE_NEW_LAPACK"),
        .define("ACCELERATE_LAPACK_ILP64"),
    ]
    + versionDefines.map { CXXSetting.define($0.0, to: $0.1) }
    + [.define("NDEBUG", .when(configuration: .release))]
    + cxxArchSettings

let cwhisperFrameworks: [LinkerSetting] =
    [.linkedFramework("Foundation")] + archFrameworks + [.linkedFramework("Accelerate")]

let package = Package(
    name: "VoiceType",
    platforms: [.macOS(.v14)],
    targets: [
        // C/C++/ObjC target: whisper + ggml (+ Metal backend on arm64), no cmake.
        .target(
            name: "CWhisper",
            path: "Sources/CWhisper",
            exclude: sharedExcludes + archExcludes,
            sources: sharedSources + archSources,
            publicHeadersPath: "include",
            cSettings: cSettings,
            cxxSettings: cxxSettings,
            linkerSettings: cwhisperFrameworks
        ),
        .executableTarget(
            name: "VoiceType",
            dependencies: ["CWhisper"],
            path: "Sources/VoiceType",
            swiftSettings: [
                // The CWhisper module map's shim #includes whisper.h, which in
                // turn includes ggml.h/ggml-cpu.h. SwiftPM doesn't propagate the
                // C target's headerSearchPaths to the importer, so make those
                // dirs visible to the Clang importer here (paths relative to the
                // package root).
                .unsafeFlags([
                    "-Xcc", "-ISources/CWhisper/whisper.cpp/include",
                    "-Xcc", "-ISources/CWhisper/whisper.cpp/ggml/include",
                ]),
            ],
            linkerSettings: [
                .linkedFramework("AppKit"),
                .linkedFramework("AVFoundation"),
                .linkedFramework("ApplicationServices"),
            ]
        ),
        .testTarget(
            name: "VoiceTypeTests",
            dependencies: ["VoiceType"],
            path: "Tests/VoiceTypeTests"
        ),
    ],
    cxxLanguageStandard: .cxx17
)
